# Generated by Django 6.0.4 on 2026-04-09 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('BIKE', 'Bike'), ('EV', 'Electric Vehicle')], max_length=10, unique=True)),
                ('base_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ev_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('BIKE', 'Bike'), ('EV', 'Electric Vehicle')], max_length=10)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=40)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('lot', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('SMALL', 'Small (Bike)'), ('MEDIUM', 'Medium (Car / EV)'), ('LARGE', 'Large (Truck)')], max_length=10)),
                ('has_ev_charger', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.floor')),
            ],
            options={
                'ordering': ['floor', 'slot_number'],
                'unique_together': {('floor', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parking.vehicle')),
            ],
        ),
    ]
